### PR TITLE
Fix bars in distribution plot

### LINKED ISSUE #34: Bars in distrubtion plot not consistent
In the following example the bars of `Truth` are not consistently visualized:

```python
import matplotlib.pyplot as plt
import numpy as np

import audplot


np.random.seed(0)

N = 1000

truth = np.random.normal(-0.25, 1.0, N)
p1 = np.random.uniform(0.25, 1.0, N)
p2 = np.random.uniform(0.25, 1.0, N)

fig, axs = plt.subplots(1, 2)

audplot.distribution(truth, p1, ax=axs[0])
audplot.distribution(truth, p2, ax=axs[1])
plt.show()
```

image

### PR DESCRIPTION
**Pull request by frankenjoe**
Closes #34 

image

~~This fixes the problem of inconsistent bars, but has the downside that we replace the frequency count with density. So maybe we should add an option to switch between the two solutions?~~

### CODE REVIEW

**Comment by hagenw** [comment]
If you would like to have an option to switch what to show on the y-axis, I see two options:

Use `frequency` as the other option instead of `count` as this has not the problems you have shown in https://github.com/audeering/audplot/issues/34#issuecomment-970044443

frequency

Another solution would be to provide the `count` option, but also disable the `common_bins` and `kde_kws` settings then (basically use what we had before this pull request for this option).

But I would also not over complicate it here and would prefer to have just one option. `count` is anyway not absolute as it depends on the bin width. `density` is easy to interpret, but you cannot easily see if one database has more samples than another. `frequency` is not so easy to understand, but you can see differences between the actual number of samples in the database.

So, I think I would stay with `density` or maybe go with `frequency`.

**Comment by frankenjoe** [comment]
> So, I think I would stay with `density` or maybe go with `frequency`.

I have no strong opinion, what is your preference?

**Comment by hagenw** [comment]
I think `frequency` shows slightly more information, so maybe we switch to `frequency`.

**Comment by frankenjoe** [comment]
> I think `frequency` shows slightly more information, so maybe we switch to `frequency`.

done

**Pull request merged**
